name: CI

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_DB: gumboard
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      GITHUB_CLIENT_ID: dummy-client-id
      GITHUB_CLIENT_SECRET: dummy-client-secret
      AUTH_SECRET: sample-auth-secret
      AUTH_URL: http://localhost:3000
      TEST_DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/gumboard"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/gumboard"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E Tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
